Lambda Expressions
MaxVortman/F_Sharp_Homework pull request #12
Opened 2018-04-08 13:58 UTC by MaxVortman

2018-05-16 15:45 UTC, yurii-litvinov requested changes

2018-05-16 15:45 UTC, yurii-litvinov commented on F_Sharp_4/beta_redaction.tex
> +%% Compile and read me!
Мм, не похоже на решение 4.1 :)

2018-09-15 19:58 UTC, yurii-litvinov commented on F_Sharp_4/beta_reduction.tex
> +\longrightarrow_\beta\,(\lambda b.b\,b)\,(\lambda b.b\,b)\,b\,\longrightarrow_\beta\,b\,b\,b$
А как получился последний шаг? По правилам "(λb.b b) (λb.b b) b" надо читать как "((λb.b b) (λb.b b)) b", и тогда b нельзя применить к лямбде.

2018-09-16 07:42 UTC, yurii-litvinov commented on F_Sharp_4/beta_reduction.tex
> +\longrightarrow_\beta\\((\lambda b.b\,b)\,(\lambda b.b\,b)\,(\lambda b.b\,b)\,(\lambda b.b\,b))\,b\,
Неееет :) Мы вместо b подставляем \lambda b.b b в \lambda b.b b, при этом аргумент-то исчезает. Это же расходящийся комбинатор.

2018-09-16 08:01 UTC, MaxVortman commented on F_Sharp_4/beta_reduction.tex
> +\longrightarrow_\beta\\((\lambda b.b\,b)\,(\lambda b.b\,b)\,(\lambda b.b\,b)\,(\lambda b.b\,b))\,b\,
@yurii-litvinov почему аргумент исчезает? Я вижу, что это расходящийся, но b тогда не исчезает, а терм становится все шире, нет?

2018-09-16 08:05 UTC, yurii-litvinov requested changes

2018-09-16 08:05 UTC, yurii-litvinov commented on F_Sharp_4/Library.fs
> -namespace F_Sharp_4
Library.fs --- не лучшее название для файла :)

2018-09-16 08:05 UTC, yurii-litvinov commented on F_Sharp_4/Library.fs
> +let (^) (A :Term) (B : Term) = Application(A, B)
Стайлгайд хочет, чтобы параметры назывались со строчной

2018-09-16 08:05 UTC, yurii-litvinov commented on F_Sharp_4/Library.fs
> +let pods (F : Term) (x : Term) =
pods --- стручки? Интересное название для функции, кажется, выполняющей подстановку. Кстати, если идея была именно в операции подстановки, лучше было бы принимать терм, в который мы хотим подставить, вместо какой переменной мы хотим подставить и терм, который мы хотим подставить в первый терм. Тут функция сама проявляет интеллект и смотрит, не абстракция ли терм F, что несколько маскирует смысл функции.

2018-09-16 08:05 UTC, yurii-litvinov commented on F_Sharp_4/Library.fs
> +        let deptha = depth a
Имена, различающиеся только регистром --- не очень, легко запутаться.

2018-09-16 08:05 UTC, yurii-litvinov commented on F_Sharp_4/Library.fs
> +            |Abstraction(s, r) -> s * postVarInternal r
Если s не входит свободно в x, иначе произойдёт связывание и всё станет плохо. Тут самое интересное в этой задаче --- посчитать множество свободных переменных и при необходимости сделать альфа-преобразование.

2018-09-22 11:10 UTC, yurii-litvinov approved these changes
Да, теперь всё примерно так. Зачтены.

2018-09-22 11:10 UTC, yurii-litvinov commented on F_Sharp_4/beta_reduction.tex
> +\longrightarrow_\beta\\((\lambda b.b\,b)\,(\lambda b.b\,b))\,b$
Да, вот теперь всё правильно, зачтена.

2018-09-22 11:10 UTC, yurii-litvinov commented on F_Sharp_4/LambdaExpressionInterpreter.fs
> +        |_ -> raise NormalizedFormNotFoundException
Хм, наверное, бывают термы, которые при редукции сначала увеличивают свою высоту, потом, тем не менее, сходятся к нормальной форме. Но это можно было и не делать, интерпретатору разрешалось зависать на термах, не имеющих нормальной формы.

2018-09-22 11:10 UTC, yurii-litvinov commented on F_Sharp_4/LambdaExpressionInterpreter.fs
> +        let rec postVarInternal (g : Term) =
Почему "post"? :)

2018-09-22 11:10 UTC, yurii-litvinov commented on F_Sharp_4/LambdaExpressionInterpreter.fs
> +    let alfaReduction (setOfVar : Set<string>) (mainTerm : Term) =
Я бы это назвал "alphaConversion". Редукции-то тут нет никакой

2018-09-22 12:47 UTC, MaxVortman commented on F_Sharp_4/LambdaExpressionInterpreter.fs
> +        |_ -> raise NormalizedFormNotFoundException
@yurii-litvinov за высоту я беру количество связей в терме. По идее после операции подстановки как минимум на одну связь должо стать меньше.

2018-09-22 13:54 UTC, yurii-litvinov commented on F_Sharp_4/LambdaExpressionInterpreter.fs
> +        |_ -> raise NormalizedFormNotFoundException
А. точно, там же складываются высоты, а не берётся максимум. Тогда да, похоже на правду.

2018-10-05 10:33 UTC, merged