Phonebook
MaxVortman/F_Sharp_Homework pull request #15
Opened 2018-04-23 22:25 UTC by MaxVortman

2018-05-15 18:02 UTC, DedSec256 commented
Не, ну всё фигня, переделывай

2018-05-15 18:05 UTC, DedSec256 requested changes
Так. Я всё понимаю, ты ММ и всё такое, но тут попахивает ПМ-ПУ

2018-05-15 18:05 UTC, DedSec256 commented on F_Sharp_Homework.sln
> +		{62077EB4-3019-4E90-910F-F306B5ABE9E7}.Debug|x64.ActiveCfg = Debug|Any CPU
ето шо за бессвязный набор букав

2018-06-04 21:49 UTC, DedSec256 reviewed
OMG

2018-06-04 21:49 UTC, DedSec256 commented on Phonebook(Task5)/UIFactory.fs
> +                             contactBook.Add contact
лучше бы оставил, как было.

2018-06-04 21:50 UTC, DedSec256 commented on Phonebook(Task5)/UIFactory.fs
> +                             contactBook.Add contact
Это мы тестим гит в HwProj, не пугайтесь.

2018-06-05 09:19 UTC, yurii-litvinov requested changes

2018-06-05 09:19 UTC, yurii-litvinov commented on Phonebook(Task5)/Contact.fs
> +type Contact(name : string, number : string) =
Тут бы ещё комментарии не помешали. Целый класс же. Кстати, зачем ему null? Есть же option. Null-ы нужны, только если мы хотим пользоваться кодом на C#, который хочет именно null-ы

2018-06-05 09:19 UTC, yurii-litvinov commented on Phonebook(Task5)/ContactBook.fs
> +    member this.Add contact = this.Contacts <- (contact :: this.Contacts)
В этой задаче мутабельные штуки были ещё запрещены. В объектно-ориенитрованном стиле телефонную книгу написать любой может :)

2018-09-29 12:02 UTC, DedSec256 commented on Phonebook(Task5)/UI.fs
> +            printfn "%s" v.Title
а если я захочу выводить не в консоль?

2018-10-01 08:31 UTC, yurii-litvinov requested changes
Хочется ещё немного рефакторинга в сторону чисто функционального стиля

2018-10-01 08:31 UTC, yurii-litvinov commented on Phonebook(Task5)/Contact.fs
> +    member val Number = number with get, set
Тоже мутабельные штуки. Как будто на Java написано :)

2018-10-01 08:31 UTC, yurii-litvinov commented on Phonebook(Task5)/ContactBook.fs
> +    member this.Add contact = this.Contacts <- (contact :: this.Contacts)
И тут. Нельзя мутабельность, в частности, сеттеры и `<-`

2018-10-01 08:31 UTC, yurii-litvinov commented on Phonebook(Task5)/ICommand.fs
> +type PrintContactsCommand(title : string, action : unit -> unit) =
Да даже интерфейсы --- это как-то не по-ФПшному. Это же просто один большой Discriminated Union

2018-10-01 08:31 UTC, yurii-litvinov commented on Phonebook(Task5)/Serializer.fs
> +        let stream = createStream path FileMode.Create
use. А то вдруг где-нить исключение --- файл не закроют

2018-10-01 08:31 UTC, yurii-litvinov commented on Phonebook(Task5)/UI.fs
> +    let commands = new Dictionary<int, ICommand>()
Мутабельные типы данных sind verboten :)

2018-10-01 14:45 UTC, MaxVortman commented on Phonebook(Task5)/Contact.fs
> +    member val Number = number with get, set
Как по мне, больше на Kotlin похоже.

2018-10-01 15:13 UTC, yurii-litvinov commented on Phonebook(Task5)/Contact.fs
> +    member val Number = number with get, set
Это правда :) Но с точки зрения F# что Java, что Kotlin --- одно и то же

2018-10-01 22:20 UTC, DedSec256 commented on Phonebook(Task5)/Serializer.fs
> +        let stream = createStream path FileMode.Create
@yurii-litvinov, я даже не сразу поверил, что он мог такое допустить.  Это немыслимо: мне проще поверить в то, что стримы у Джавы - нормальный аналог Linq, чем в то, что Максим не написал use.

2018-10-04 14:49 UTC, yurii-litvinov approved these changes
Хорошо, зачтена

2018-10-04 14:49 UTC, yurii-litvinov commented on Phonebook(Task5).Test/PhonebookTests.fs
> +        let path = @"C:\\testSerialize.test"
Ой, абсолютный путь

2018-10-05 10:35 UTC, merged