Solved reverse problem.
MaxVortman/F_Sharp_Homework pull request #2
Opened 2018-02-19 14:46 UTC by MaxVortman

2018-02-19 15:17 UTC, yurii-litvinov requested changes

2018-02-19 15:17 UTC, yurii-litvinov commented on F_Sharp_1/Program.fs
> +let reverseList list = [for i in (List.length list) - 1  .. -1 .. 0 -> list.[i]]
Не, for в первых домашках использовать пока нельзя (хочется более "функционального" решения), и индексер у списка работает за линейное время, так что суммарная трудоёмкость получилась квадратичная.

2018-02-20 09:07 UTC, MaxVortman commented
Что-то мне подсказывает, что тут тоже за n^2.

2018-02-20 13:25 UTC, MaxVortman commented
Сейчас должно быть за линию.

2018-02-20 13:48 UTC, yurii-litvinov approved these changes
Всё так, зачтена

2018-02-20 14:23 UTC, merged