Countevennumbers
MaxVortman/F_Sharp_Homework pull request #8
Opened 2018-02-28 16:38 UTC by MaxVortman

2018-03-22 06:42 UTC, yurii-litvinov requested changes
В целом всё так, но хочу юнит-тесты отдельно

2018-03-22 06:42 UTC, yurii-litvinov commented on F_Sharp_3/Program.fs
> +        let ``Count even numbers of list [0 .. 10] should be equal 6`` =
Тесты лучше держать в отдельном проекте --- когда программа поставляется пользователю, юнит-тесты в байт-коде ему не хочется.

2018-03-22 06:42 UTC, yurii-litvinov commented on F_Sharp_3/Program.fs
> +            list |> List.map (fun x -> if x % 2 = 0 then 1 else 0) |> List.fold (+) 0
`List.fold (+) 0` --- это то же, что `List.reduce (+)` или `List.sum`

2018-03-28 06:01 UTC, yurii-litvinov requested changes

2018-03-28 06:01 UTC, yurii-litvinov commented on F_Sharp_3.Test/Program.fs
> +    [<Test>]
dotnet test говорит, что нет доступных тестов. У Вас работает, что ли?

2018-03-28 09:08 UTC, MaxVortman commented on F_Sharp_3.Test/Program.fs
> +    [<Test>]
@yurii-litvinov работает, если запустить проект теста. При успешном прохождении не вылазят ошибки.
Я пробовал через dotnet test, но что-то ничего не получилось. Облазил интернет. Информации об этом почти нет, а та, что есть не годна. 
Ставил NUnit3TestAdapter, NUnit и прочее. Сверял версии. Ничего не пашет. Выводит это:
![image](https://user-images.githubusercontent.com/17088719/38019602-b7c74080-3280-11e8-81b6-b9075ea94253.png)

2018-03-28 09:09 UTC, MaxVortman commented on F_Sharp_3.Test/Program.fs
> +    [<Test>]
Еще чуть-чуть и перейду на mstest.

2018-03-28 09:30 UTC, yurii-litvinov commented on F_Sharp_3.Test/Program.fs
> +    [<Test>]
Да ну не может быть, тут ведь правда нет тестов. `for first option` --- это значение, а не функция, его нельзя запустить :)

2018-03-28 09:53 UTC, MaxVortman commented on F_Sharp_3.Test/Program.fs
> +    [<Test>]
@yurii-litvinov  да, ура. Спасибо.

2018-03-29 08:41 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена

2018-03-29 08:52 UTC, merged