Maptree
MaxVortman/F_Sharp_Homework pull request #9
Opened 2018-02-28 17:27 UTC by MaxVortman

2018-03-25 19:58 UTC, yurii-litvinov requested changes
Опять-таки, всё так (ну, задача простая), но надо больше тестов, и вынести их в отдельынй проект. И можно не делать по новой ветки для каждой задачи, а, пока домашки простые, делать все задачи одной домашки в одной ветке. А то вот эта не от мастера отведена, а от предыдущего решения, поэтому в диффе лишний код, не относящийся к этой задаче. Можно не править, но на будущее :)

2018-03-25 19:58 UTC, yurii-litvinov commented on F_Sharp_3/Program.fs
> +        binTree |> mapTree (fun x -> pown x 2) |> should equal expectedBinTree
Но это только тест на нормальный режим работы, неплохо бы ещё проверить "странные" случаи

2018-03-27 08:07 UTC, MaxVortman commented on F_Sharp_3/Program.fs
> +        binTree |> mapTree (fun x -> pown x 2) |> should equal expectedBinTree
@yurii-litvinov что именно подразумевается под "странными" случаями? Map пустого дерева?

2018-03-29 08:43 UTC, yurii-litvinov approved these changes
Тоже зачтена

2018-03-29 08:53 UTC, merged